# Generated by Django 4.2 on 2023-06-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='active',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='deleted_at',
        ),
    ]
