# Generated by Django 4.2 on 2023-06-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_cliente_active_remove_cliente_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
