# Generated by Django 4.2 on 2023-06-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cliente_active_cliente_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
