# Generated by Django 4.2 on 2023-06-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_active'),
        ('cliente', '0007_alter_cliente_active'),
    ]

    operations = [
    ]
