# Generated by Django 4.2 on 2023-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_alter_libro_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
