# Generated by Django 4.2 on 2023-06-19 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(blank=True, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientes', to='cliente.cliente')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='libros', to='libro.libro')),
            ],
        ),
    ]
