# Generated by Django 4.2 on 2023-05-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_libro_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
