# Generated by Django 4.2 on 2023-05-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_alter_autor_nombre'),
        ('genero', '0001_initial'),
        ('libro', '0003_rename_nombre_libro_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autor.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='Borrado'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genero.genero', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
