# Generated by Django 4.1.7 on 2023-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('domicilio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
                ('ISBN', models.CharField(max_length=18)),
            ],
        ),
    ]
