# Generated by Django 4.2 on 2023-04-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='USBN',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.CharField(default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
